# Example configuration entry
template:
    sensor:
      # Keep track how many time device is on today past midnight
      - name: Light is on
        state: '{{ ( ( as_timestamp(now()) - as_timestamp(strptime("06.07.2018", "%d.%m.%Y")) ) / 86400 ) | round }}'
        unit_of_measurement: "Minutes"

# Example configuration.yaml entry
sensor:
  - platform: history_stats
    name: Lamp ON today
    entity_id: light.my_lamp
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

# enable the recorder integration (optional)
recorder:


# light switch sensor
template:
  - binary_sensor:
      - name: "Grow Light On"
        state: "{{ is_state('switch.grow_light', 'on') }}"
        device_class: "light"
        
